basket/urls.py
from django.urls import path
from basket import views


urlpatterns = [
    path('', views.player_list, name="player"),
    path('player_list', views.player_list, name="player_list"),
    path('player_add', views.player_add, name="player_add"),
    path('player_edit/<int:pk>/', views.player_edit, name="player_edit"),
    path('player_delete/<int:pk>/', views.player_del, name="player_delete"),
    path('team_list', views.team_list, name="team_list"),
    path('team_add', views.team_add, name="team_add"),
    path('team_edit/<int:pk>/', views.team_edit, name="team_edit"),
    path('team_delete/<int:pk>/', views.team_del, name="team_delete"),
    path('coach_list', views.coach_list, name="coach_list"),
    path('coach_add', views.coach_add, name="coach_add"),
    path('coach_edit/<int:pk>/', views.coach_edit, name="coach_edit"),
    path('coach_delete/<int:pk>/', views.coach_del, name="coach_delete"),
    path('match_list', views.match_list, name="match_list"),
    path('match_delete/<int:pk>/', views.match_del, name="match_delete"),
    path('match_add', views.match_add, name="match_add"),
    path('match_edit/<int:pk>/', views.match_edit, name="match_edit"),
    path('teamcompose_list', views.teamcompose_list, name="teamcompose_list"),
    path('teamcompose_delete/<int:pk>/', views.teamcompose_del, name="teamcompose_delete"),
    path('teamcompose_add', views.teamcompose_add, name="teamcompose_add"),
    path('teamcompose_edit/<int:pk>/', views.teamcompose_edit, name="teamcompose_edit"),
    path('view/<int:player_id>', views.detail, name="player_detail"),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from basket.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name="index"),
    path('basket/', include('basket.urls'), name='basket'),
    path('auth/', include('auth_basket.urls'), name='auth'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basket/models.py
from django.db import models
from basket.defines import POSITION_PLAYER_CHOICES
from django.contrib.auth.models import User

class Team(models.Model):
    name = models.CharField(max_length=120)
    description = models.TextField()
    logo = models.ImageField(upload_to='logos')
    code = models.CharField(max_length=3)

    def __str__(self):
        return self.name

class Player(models.Model):
    name = models.CharField(max_length=120)
    nickname = models.CharField(max_length=120)
    birthday = models.DateField()
    age = models.PositiveIntegerField()
    email = models.EmailField()
    height = models.PositiveIntegerField(help_text="Altura en cm")
    weight = models.PositiveIntegerField(help_text="Peso en kilos")
    picture = models.ImageField(upload_to='picture_players')
    position = models.CharField(max_length=60, choices=POSITION_PLAYER_CHOICES)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    rut = models.PositiveIntegerField()
    dv = models.CharField(max_length=1)

    def full_rut(self):
        return '{}-{}' . format(self.rut, self.dv)

    def __str__(self):
        return self.name

class Coach(models.Model):
    user = models.OneToOneField(User,null=True,on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    age = models.PositiveIntegerField()
    email = models.EmailField()
    nickname = models.CharField(max_length=120)
    team = models.OneToOneField(Team,null=True,on_delete=models.SET_NULL)

    rut = models.PositiveIntegerField()
    dv = models.CharField(max_length=1)

    def __str__(self):
        return self.name

    def full_rut(self):
        return '{}-{}' . format(self.rut, self.dv)

class Match(models.Model):
    date = models.DateTimeField(null=True,default=None)
    name = models.CharField(max_length=100)
    team1 = models.ForeignKey(Team,default=None,related_name="Team1",on_delete=models.CASCADE)
    team2 = models.ForeignKey(Team,default=None,related_name="Team2",on_delete=models.CASCADE)

class TeamCompose(models.Model):
    players = models.ManyToManyField(Player, default=None,)
    author = models.ForeignKey(Coach,null=True,default=None,on_delete=models.SET_NULL)
    match = models.ForeignKey(Match,null=True,default=None,on_delete=models.SET_NULL)


    

basket/forms.py
from django import forms
from basket.models import Player,Team,Coach,Match,TeamCompose


class PlayerForm(forms.ModelForm):
    class Meta:
        model = Player
        fields = ['rut', 'dv', 'name', 'nickname', 'birthday', 'age', 'email', 'height', 'weight', 'picture', 'position', 'team']
        widgets = {
            'birthday': forms.DateInput(attrs={'class':'datepicker'}),
        }

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = ['name', 'description', 'logo','code']

class CoachForm(forms.ModelForm):
    class Meta:
        model = Coach
        fields = ['name', 'age', 'email', 'nickname', 'team', 'rut', 'dv']

class MatchForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ['name','team1','team2']
        widgets = {
            'date': forms.DateInput(attrs={'class':'datepicker'}),
        }

class TeamComposeForm(forms.ModelForm):
    class Meta:
        model = TeamCompose
        fields = ["players","match"]

    players = forms.ModelMultipleChoiceField(queryset=Player.objects.all())

    def __init__(self, *args, **kwargs):
        if kwargs.get('instance'):
            initial = kwargs.setdefault('initial', {})
            initial['players'] = [t.pk for t in kwargs['instance'].topping_set.all()]

        forms.ModelForm.__init__(self, *args, **kwargs)

    def save(self):
        instance = forms.ModelForm.save(self)
        instance.topping_set.clear()
        for player in self.cleaned_data['players']:
            instance.topping_set.add(player)

basket/views.py
from django.shortcuts import render
from basket.models import Player,Team,Coach,TeamCompose,Match
from basket.forms import PlayerForm,TeamForm,MatchForm,CoachForm,TeamComposeForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required

def index(request):
    data = {
    }

    template_name = 'index.html'
    return render(request,template_name,data)

def player_list(request):
    data = {}

    # SELECT * FROM player
    object_list = Player.objects.all().order_by('-id')

    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')

    try:
        data['object_list'] = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        data['object_list'] = paginator.page(1)
    except EmptyPage:
        data['object_list'] = paginator.page(paginator.num_pages)

    template_name = 'player/list_player.html'
    return render(request, template_name, data)

@login_required(login_url='/auth/login')
def player_del(request,pk):
    player = Player.objects.get(pk=pk)
    player.delete()

    return HttpResponseRedirect(reverse("player_list"))

def player_add(request):
    data = {}
    if request.method == "POST":
        data['form'] = PlayerForm(request.POST, request.FILES)
        if data['form'].is_valid():
            # aca el formulario valido
            data['form'].save()

            return redirect('player_list')

    else:
        data['form'] = PlayerForm()

    data["titulo"] = "Agregar"
    template_name = 'player/add_player.html'
    return render(request, template_name, data)

@login_required(login_url='/auth/login')
def player_edit(request,pk):
    data = {}
    player = Player.objects.get(pk=int(pk))
    if request.method == "POST":
        data['form'] = PlayerForm(request.POST, request.FILES, instance=player)
        if data['form'].is_valid():
            # aca el formulario valido
            data['form'].save()
            return redirect('player_list')

    else:
        print("Este es el Player ", player)
        data['form'] = PlayerForm(instance=player)

    data["titulo"] = "Editar"
    template_name = 'player/add_player.html'
    return render(request, template_name, data)


def team_list(request):
    data = {}

    # SELECT * FROM player
    object_list = Team.objects.all().order_by('-id')

    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')

    try:
        data['object_list'] = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        data['object_list'] = paginator.page(1)
    except EmptyPage:
        data['object_list'] = paginator.page(paginator.num_pages)

    template_name = 'team/list_team.html'
    return render(request, template_name, data)

@login_required(login_url='/auth/login')
def team_del(request,pk):
    team = Team.objects.get(pk=pk)
    team.remove()

    return HttpResponseRedirect(reverse("team_list"))

def team_add(request):
    data = {}
    if request.method == "POST":
        data['form'] = TeamForm(request.POST, request.FILES)
        if data['form'].is_valid():
            # aca el formulario valido
            data['form'].save()

            return redirect('team_list')

    else:
        data['form'] = TeamForm()

    data["titulo"] = "Agregar"
    template_name = 'team/add_team.html'
    return render(request, template_name, data)

@login_required(login_url='/auth/login')
def team_edit(request,pk):
    data = {}
    team = Team.objects.get(pk=int(pk))
    if request.method == "POST":
        data['form'] = TeamForm(request.POST, request.FILES, instance=team)
        if data['form'].is_valid():
            # aca el formulario valido
            data['form'].save()
            return redirect('team_list')

    else:
        print("Este es el Team ", team)
        data['form'] = TeamForm(instance=Team)

    data["titulo"] = "Editar"
    template_name = 'team/add_team.html'
    return render(request, template_name, data)

def coach_list(request):
    data = {}

    # SELECT * FROM player
    object_list = Coach.objects.all().order_by('-id')

    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')

    try:
        data['object_list'] = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        data['object_list'] = paginator.page(1)
    except EmptyPage:
        data['object_list'] = paginator.page(paginator.num_pages)

    template_name = 'coach/list_coach.html'
    return render(request, template_name, data)


@login_required(login_url='/auth/login')
def coach_del(request,pk):
    coach = Coach.objects.get(pk=pk)
    coach.delete()

    return HttpResponseRedirect(reverse("coach_list"))

def coach_add(request):
    data = {}
    if request.method == "POST":
        data['form'] = CoachForm(request.POST)
        username = request.POST["rut"]
        password = request.POST["nickname"]+request.POST["dv"]
        print("Esta esl a password: ",password)
        user = User.objects.create_user(username=username,password=password)
        user.save()
        if data['form'].is_valid():
            # aca el formulario valido
            coach=data['form'].save()
            coach.user = user
            coach.save()
            return redirect('coach_list')

    else:
        data['form'] = CoachForm()

    data["titulo"] = "Agregar"
    template_name = 'coach/add_coach.html'
    return render(request, template_name, data)

@login_required(login_url='/auth/login')
def coach_edit(request,pk):
    data = {}
    coach = Coach.objects.get(pk=int(pk))
    if request.method == "POST":

        data['form'] = CoachForm(request.POST, instance=coach)
        if data['form'].is_valid():
            # aca el formulario valido
            data['form'].save()
            return redirect('coach_list')

    else:
        print("Este es el Coach ", coach)
        data['form'] = CoachForm(instance=coach)

    data["titulo"] = "Editar"
    template_name = 'coach/add_coach.html'
    return render(request, template_name, data)

def teamcompose_list(request):
    data = {}

    # SELECT * FROM player
    object_list = TeamCompose.objects.filter(author=request.user.coach).order_by('-id')

    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')

    try:
        data['object_list'] = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        data['object_list'] = paginator.page(1)
    except EmptyPage:
        data['object_list'] = paginator.page(paginator.num_pages)

    template_name = 'teamcompose/list_teamcompose.html'
    return render(request, template_name, data)


@login_required(login_url='/auth/login')
def teamcompose_del(request,pk):
    teamcompose = TeamCompose.objects.get(pk=pk)
    teamcompose.delete()

    return HttpResponseRedirect(reverse("teamcompose_list"))

@login_required(login_url='/auth/login')
def teamcompose_add(request):
    data = {}
    coach = request.user.coach
    if request.method == "POST":
        players = request.POST.get_list("players[]")
        match = request.POST["match"]
        match = Match.objects.get(pk=int(match))
        teamcompose = TeamCompose.objects.create(match=match)
        teamcompose.save()
        for player in players:
            player = Player.objects.get(pk=int(player))
            teamcompose.players.add(player)
            teamcompose.save()
        template_name = 'teamcompose/list_teamcompose.html'
        return render(request, template_name, data)

    else:
        players = Player.objects.filter(team=coach.team)
        matches = Match.objects.filter(Q(team1=coach.team) | Q(team2=coach.team))
        data["players"] = players
        data["matches"] = matches

    data["titulo"] = "Agregar"
    template_name = 'teamcompose/add_teamcompose.html'
    return render(request, template_name, data)

@login_required(login_url='/auth/login')
def teamcompose_edit(request,pk):
    data = {}
    teamcompose = TeamCompose.objects.get(pk=int(pk))
    if request.method == "POST":
        data['form'] = TeamComposeForm(request.POST, request.FILES, instance=teamcompose)
        if data['form'].is_valid():
            # aca el formulario valido
            data['form'].save()
            return redirect('player_list')

    else:
        print("Este es el TeamCompose ", teamcompose)
        data['form'] = TeamComposeForm(instance=teamcompose)

    data["titulo"] = "Editar"
    template_name = 'teamcompose/add_teamcompose.html'
    return render(request, template_name, data)

def match_list(request):
    data = {}

    # SELECT * FROM player
    object_list = Match.objects.all().order_by('-id')

    paginator = Paginator(object_list, 10)
    page = request.GET.get('page')

    try:
        data['object_list'] = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        data['object_list'] = paginator.page(1)
    except EmptyPage:
        data['object_list'] = paginator.page(paginator.num_pages)

    template_name = 'match/list_match.html'
    return render(request, template_name, data)


@login_required(login_url='/auth/login')
def match_del(request,pk):
    match = Match.objects.get(pk=pk)
    match.delete()

    return HttpResponseRedirect(reverse("match_list"))

def match_add(request):
    data = {}
    if request.method == "POST":
        data['form'] = MatchForm(request.POST, request.FILES)
        if data['form'].is_valid():
            # aca el formulario valido
            match = data['form'].save()
            match.date = request.POST["date"]
            match.save()

basket/templates/teamcompose/add_teamcompose.html
{% extends "base.html"%} {% load bootstrap4 %} {% load static %} 
{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css" rel="stylesheet" />
{% endblock css%}
{% block title %} {{titulo}} una Nomina {% endblock title%} {% block content %}
<div class="row">
	<div class="col-lg-8 offset-lg-2 col-md-8 offset-md-2">
		<h1 class="text-center" style="margin-top:30px;">{{titulo}} Nomina</h1>
		<hr>
		<form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
			<div class="form-group row">
				<label class="col-md-3 col-form-label" for="id_match">Match</label>
				<div class="col-md-9">
					<select name="match" class="form-control" id="id_match" title="" required="">
						{% for match in matches %}
						<option value="{{match.pk}}">{{match.name}}</option>
						{% endfor %}
					</select>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-md-3 col-form-label" for="id_players">Players</label>
				<div class="col-md-9">
					<select name="players" class="form-control select2 select2-with-search" multiple="multiple" id="id_players" title="" required="">
						{% for player in players %}
						<option value="{{player.pk}}">{{player.name}}</option>
						{% endfor %}
					</select>
				</div>
			</div>
			
			<input value="Enviar" class="btn btn-primary btn-lg btn-block" type="submit">
		</form>
		<br>
	</div>
</div>
{% endblock content %} {% block javascript %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script>
	$(document).ready(function () {
		$(".select2").select2({maximumSelectionSize:12, minimumSelectionSize:4});
		$("#tc_list").addClass("active");
		
		$('.datepicker').datepicker({ format: 'dd/mm/yyyy' });
		
	});
</script> {% endblock javascript %}

basket/templates/teamcompose/list_teamcompose.html
{% extends "base.html" %}
{% block title %}
Lista de Nominas
{% endblock title %}
{% block content %}
<div class="row titulo">
	<h1>Lista de Nominas</h1>
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-12">
				<input type="text" id="search" class="form-control" placeholder="Que estas buscando?...">
				<br>
			</div>
			<div class="col-md-12 m-t-1">
				<table class="table table-striped">
					<thead>
						<tr>
							<th scope="col">Nombre</th>
							<th scope="col">Descripcion</th>
							<th scope="col">Logo</th>
							<th scope="col">Acronimo</th>
							{% if request.user.is_staff %}
							<th scope="col">Acciones</th>
							{% endif %}
						</tr>
					</thead>
					<tbody id="te_table">
						{% for team in object_list %}
						<tr>
							<td>{{team.name}}</td>
							<td>{{team.description}}</td>
							<td><img class="img-thumbnail img-fluid logo-team"  src="{{team.logo.url}}" alt=""></td>
							<td>{{team.code}}</td>
							{% if request.user.is_staff %}
							<td>
								<a class="btn btn-warning btn-sm" href="{% url 'team_edit' team.pk %}"><i class="fa fa-edit"></i></a>
								<a class="btn btn-danger btn-sm" href="{% url 'team_delete' team.pk %}"><i class="fa fa-times"></i></a>
							</td>
							{% endif %}
						</tr>
						{% endfor %}
		
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<div class="row">
	{% if object_list.has_next or object_list.has_previous %}
	<nav aria-label="Page navigation example">
		<ul class="pagination">
			{% if object_list.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ object_list.previous_page_number }}">Previous</a>
			</li>
			{% endif %} {% for page in object_list.paginator.page_range %}
			<li class="page-item {% if object_list.number == page %}active{% endif %}">
				<a class="page-link" href="?page={{ page }}">{{ page }}</a>
			</li>
			{% endfor %} {% if object_list.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ object_list.next_page_number }}">Next</a>
			</li>
			{% endif %}
		</ul>
	</nav>
	{% endif %}
</div>
<!-- Button trigger modal -->
<!-- Modal -->
{% comment %} <div class="modal fade" id="detallesModal" tabindex="-1" role="dialog" aria-labelledby="DetallesDeJugadores" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLongTitle">Información</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-md-4">
						<img class="mb-4 rounded-circle" src="{% static 'index.jpg' %}" alt="" width="50%" height="50%">
					</div>
					<div class="col-md-8">
						<div class="row">
							<label for="name"></label>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary">Save changes</button>
			</div>
		</div>
	</div>
</div> {% endcomment %}
{% endblock content %}
{% block javascript %}
<script>
	$(document).ready(function(){
		$("#te_list").addClass("active");
		
		$("#search").on("keyup", function() {
			var value = $(this).val().toLowerCase();
			$("#te_table tr").filter(function() {
				$(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
			});
		});

		$('#detallesModal').on('shown.bs.modal', function () {

		});
	});
</script> 
{% endblock javascript %}